name: paradedb

services:
  paradedb:
    image: paradedb/paradedb:${PARADEDB_VERSION:-latest}
    container_name: paradedb
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME:-admin}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-YourStrong@Password}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-paradedb}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD:-YourStrong@Password}
    ports:
      - "${PARADEDB_PORT:-5432}:5432"
    volumes:
      - paradedb-data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  paradedb-data:
    name: paradedb-data
