{{- if and .Values.nginx.enabled .Values.nginx.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ai-workspace.fullname" . }}
  labels:
    {{- include "ai-workspace.labels" . | nindent 4 }}
  {{- with .Values.nginx.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nginx.ingress.className }}
  ingressClassName: {{ .Values.nginx.ingress.className }}
  {{- end }}
  {{- if .Values.nginx.ingress.tls }}
  tls:
    {{- range .Values.nginx.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.nginx.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "ai-workspace.fullname" $ }}-nginx
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end }}
