{{- if .Values.apacheTika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-workspace.fullname" . }}-tika
  labels:
    {{- include "ai-workspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: tika
spec:
  type: {{ .Values.apacheTika.service.type }}
  ports:
  - port: {{ .Values.apacheTika.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "ai-workspace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tika
{{- end }}
