name: sql-server
services:
    sql-server:
        ports:
        - ${SQL_SERVER_PORT:-1433}:1433
        environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd}
        image: mcr.microsoft.com/mssql/server:2022-latest
        volumes:
        - sqlserver-data:/var/opt/mssql
