name: rabbitmq

services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-management}
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-YourStrong@Password}
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq-data:
    name: rabbitmq-data
  rabbitmq-log:
    name: rabbitmq-log
