name: comfyui

services:
  comfyui:
    image: xingren23/comfyui:${COMFYUI_VERSION:-comfyui-cu121-v1.0.7}
    container_name: comfyui
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
    ports:
      - "${COMFYUI_PORT:-8188}:8188"
    volumes:
      - comfyui-models:/root/ComfyUI/models
      - comfyui-input:/root/ComfyUI/input
      - comfyui-output:/root/ComfyUI/output
      - comfyui-custom-nodes:/root/ComfyUI/custom_nodes
      - comfyui-workflows:/root/ComfyUI/user/default/workflows
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  comfyui-models:
    name: comfyui-models
  comfyui-input:
    name: comfyui-input
  comfyui-output:
    name: comfyui-output
  comfyui-custom-nodes:
    name: comfyui-custom-nodes
  comfyui-workflows:
    name: comfyui-workflows
