name: qdrant

services:
  qdrant:
    image: qdrant/qdrant:${QDRANT_VERSION:-latest}
    container_name: qdrant
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=${QDRANT_ALLOW_RECOVERY_MODE:-false}
    volumes:
      - qdrant-storage:/qdrant/storage
      - qdrant-snapshots:/qdrant/snapshots
    restart: unless-stopped

volumes:
  qdrant-storage:
    name: qdrant-storage
  qdrant-snapshots:
    name: qdrant-snapshots
