name: sql-server

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:${SQL_SERVER_VERSION:-2022-latest}
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=${MSSQL_PID:-Developer}
      - MSSQL_COLLATION=${MSSQL_COLLATION:-SQL_Latin1_General_CP1_CI_AS}
    ports:
      - "${SQL_SERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    user: "0:0"

volumes:
  sqlserver-data:
    name: sqlserver-data
