{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector-search-rag.fullname" . }}-ollama
  labels:
    {{- include "vector-search-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vector-search-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
{{- end }}
