{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector-search-rag.fullname" . }}-qdrant
  labels:
    {{- include "vector-search-rag.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  type: {{ .Values.qdrant.service.type }}
  ports:
    - port: {{ .Values.qdrant.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.qdrant.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "vector-search-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
{{- end }}
