name: azurite

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:${AZURITE_VERSION:-latest}
    container_name: azurite
    ports:
      - "${AZURITE_BLOB_PORT:-10000}:10000"
      - "${AZURITE_QUEUE_PORT:-10001}:10001"
      - "${AZURITE_TABLE_PORT:-10002}:10002"
    volumes:
      - azurite-data:/data
    command: >
      azurite
      --blobPort 10000 --blobHost 0.0.0.0
      --queuePort 10001 --queueHost 0.0.0.0
      --tablePort 10002 --tableHost 0.0.0.0
      --location /data
      --loose
      --skipApiVersionCheck
      --disableProductStyleUrl
    restart: unless-stopped

volumes:
  azurite-data:
    name: azurite-data
